In [18]:
import torch

In [19]:
torch.__version__

'1.12.1'

#### 1. 데이터생성

In [30]:
# 초기화되지 않은 텐서생성
x = torch.empty(4,2) 

# 무작위로 초기화된 텐서생성 (0~1 사이)
x = torch.rand(4,2)

# 사용자가 입력한 텐서
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])

# 0, 1 로 채워진 텐서
x = torch.ones(4,2)
x = torch.zeros(4,2)

# 같은 크기를 가지는 무작위 텐서 생성
data = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
x = torch.randn_like(data,dtype=float)

In [36]:
# 타입 리턴
print(x.type())

# 타입 리턴 (자세히)
print(x.dtype)

# shape 리턴
print(x.shape)

# shape 리턴
print(x.size())

torch.DoubleTensor
torch.float64
torch.Size([4, 2])
torch.Size([4, 2])


#### 2. GPU와 CPU이동

In [43]:
x = torch.randn(3,2)
print(x)
print(x.device)

tensor([[-0.8083, -0.7392],
        [-0.9503, -1.2524],
        [-0.6635, -0.5307]])
cpu


In [44]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [45]:
x = x.to(device, torch.double)
print(x)
print(x.device)

tensor([[-0.8083, -0.7392],
        [-0.9503, -1.2524],
        [-0.6635, -0.5307]], device='cuda:0', dtype=torch.float64)
cuda:0


#### 3. 텐서연산

(1) 기본연산

In [54]:
print(torch.abs(x))
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x))
print(torch.std(x))
print(torch.prod(x))
print(torch.ceil(x))
print(torch.floor(x))

tensor([[0.8083, 0.7392],
        [0.9503, 1.2524],
        [0.6635, 0.5307]], device='cuda:0', dtype=torch.float64)
tensor(-1.2524, device='cuda:0', dtype=torch.float64)
tensor(-0.5307, device='cuda:0', dtype=torch.float64)
tensor(-0.8241, device='cuda:0', dtype=torch.float64)
tensor(0.2525, device='cuda:0', dtype=torch.float64)
tensor(0.2504, device='cuda:0', dtype=torch.float64)
tensor([[-0., -0.],
        [-0., -1.],
        [-0., -0.]], device='cuda:0', dtype=torch.float64)
tensor([[-1., -1.],
        [-1., -2.],
        [-1., -1.]], device='cuda:0', dtype=torch.float64)


(2) 행렬연산

In [95]:
x = torch.tensor([[1,2,3],[4,5,6]],dtype=float) 
y = torch.randn_like(x,dtype=float)
y_t = y.T

print(x.shape)
print(y.shape)
print(y_t.shape)

# element-wise product
print(x*y)

# 행렬연산
print(torch.matmul(x,y_t))

torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[  1.4303,  -0.8309,  -0.1673],
        [ -3.0072, -10.9429,   1.8235]], dtype=torch.float64)
tensor([[  0.4321,  -4.2172],
        [  3.3092, -12.1266]], dtype=torch.float64)


(3) 그 외 연산

In [58]:
x = torch.tensor([1,2,3,4,1,2,3,1])
x_set = torch.unique(x)

print(x)
print(x_set)

tensor([1, 2, 3, 4, 1, 2, 3, 1])
tensor([1, 2, 3, 4])


In [61]:
x = torch.tensor([1,2,3,4,1,2,3,1])
x_clamp = torch.clamp(x,1.5,2.5)

print(x)
print(x_clamp)

tensor([1, 2, 3, 4, 1, 2, 3, 1])
tensor([1.5000, 2.0000, 2.5000, 2.5000, 1.5000, 2.0000, 2.5000, 1.5000])


In [66]:
x = torch.rand(3,4)
arg = x.max(dim=0)

print(x)
print(arg)

tensor([[0.7002, 0.5021, 0.8545, 0.2372],
        [0.0192, 0.5245, 0.7978, 0.5102],
        [0.1585, 0.4971, 0.7144, 0.5225]])
torch.return_types.max(
values=tensor([0.7002, 0.5245, 0.8545, 0.5225]),
indices=tensor([0, 1, 0, 2]))
